name: tests
on:
  workflow_dispatch:
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v4

    - name: deps
      run: |
          sudo apt-get update && sudo apt-get install -y curl gpg
          curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor >bazel-archive-keyring.gpg
          sudo mv bazel-archive-keyring.gpg /usr/share/keyrings
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/bazel-archive-keyring.gpg] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
          sudo apt-get update && sudo apt-get install -y git curl wget python3 xz-utils lsb-release pkg-config bazel libicu-dev apt-transport-https gnupg
          
    - name: depot_tools
      run: |
          git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "$(pwd)/depot_tools" >> $GITHUB_PATH

    - name: fetch and build webrtc
      run: |
          mkdir webrtc-checkout
          pushd webrtc-checkout
          fetch --no-history --nohooks webrtc
          sed -i -e "s|'src/resources'],|'src/resources'],'condition':'rtc_include_tests==true',|" src/DEPS 
          gclient sync 
          mv src webrtc
          pushd webrtc
          gn gen out/Default --args='is_debug=false use_custom_libcxx=false rtc_include_tests=false rtc_build_examples=false dcheck_always_on=true rtc_use_x11=false use_rtti=true'
          ninja -C out/Default
          popd
          popd

    - name: build
      run: |
          sed -i -e 's|webrtc_path = ".*"|webrtc_path = "$(pwd)/webrtc-checkout/"|g' WORKSPACE
          bazel build ...

    - name: test
      run: | 
          bazel test ...
    
